### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by KDlamini** [BenMukebo/javascript-capstone#38]
Hi @mmsesay and @BenMukebo,

You have done an excellent job on this project 🎊 
Your interface is impressive, I love how responsive the nature of the website is. I can like items and I can also see the number of items per page. However, I notice one issue with the pop-up, I cannot scroll on the information on the window. Therefore, I cannot make or view comments. Please kindly attend to this issue.

Cheers 🥂 and happy coding 👏🏾 👏🏾 👏🏾

**Comment by BenMukebo** [comment]
Thank you @KDlamini  for your remark on our project!!
